import Link from 'next/link';

const CORE_OPPORTUNITY_PRODUCTS = [
  { slug: 'bold-98-irish-whiskey', name: 'Bold 98 Irish Whiskey' },
  { slug: 'old-smuggler-blended-scotch', name: 'Old Smuggler Blended Scotch' },
  { slug: 'the-famous-grouse-blended-scotch', name: 'The Famous Grouse Blended Scotch' },
  { slug: 'laphroaig-four-oak', name: 'Laphroaig Four Oak' },
  { slug: 'glenfiddich-18-years-old', name: 'Glenfiddich 18 Years Old' },
  { slug: 'whitley-neill-quince-gin', name: 'Whitley Neill Quince Gin' },
  { slug: 'salamanca-tequila-blanco', name: 'Salamanca Tequila Blanco' },
  { slug: 'pata-negra-reserva-2019', name: 'Pata Negra Reserva 2019' },
  { slug: 'glenfiddich-12-years-old', name: 'Glenfiddich 12 Years Old' },
  { slug: 'glenfiddich-15-years-old', name: 'Glenfiddich 15 Years Old' },
  { slug: 'glenfiddich-18-years-old', name: 'Glenfiddich 18 Years Old' },
  { slug: 'moet-chandon-ice-imperial-champagne', name: 'Moët & Chandon Ice Imperial' },
  { slug: 'moet-chandon-nectar-imperial-blanc-champagne', name: 'Moët & Chandon Nectar Imperial Blanc' },
  { slug: 'moet-chandon-rose-imperial-champagne', name: 'Moët & Chandon Rosé Imperial' },
  { slug: 'the-macallan-12-years-double-cask', name: 'The Macallan 12 Years Double Cask' },
  { slug: 'the-macallan-whisky-15-years-double-cask', name: 'The Macallan 15 Years Double Cask' },
  { slug: 'the-macallan-double-cask-18-years', name: 'The Macallan Double Cask 18 Years' },
  { slug: 'jameson-black-barrel', name: 'Jameson Black Barrel' },
  { slug: 'jameson-stout-edition-irish-whiskey', name: 'Jameson Stout Edition Irish Whiskey' },
  { slug: 'martell-blue-swift', name: 'Martell Blue Swift' },
  { slug: 'martell-vs', name: 'Martell VS Cognac' },
  { slug: 'martell-chanteloup-xxo', name: 'Martell Chanteloup XXO Cognac' },
  { slug: 'martell-xo', name: 'Martell XO Cognac' },
  { slug: 'four-cousins-cabernet-sauvignon-2024', name: 'Four Cousins Cabernet Sauvignon 2024' },
  { slug: 'four-cousins-directors-reserve-merlot-2021', name: "Four Cousins Director's Reserve Merlot 2021" },
  { slug: 'four-cousins-dry-rose', name: 'Four Cousins Dry Rosé' },
  { slug: 'four-cousins-merlot-2024', name: 'Four Cousins Merlot 2024' },
  { slug: 'four-cousins-pinotage-2023', name: 'Four Cousins Pinotage 2023' },
  { slug: 'four-cousins-sauvignon-blanc', name: 'Four Cousins Sauvignon Blanc' },
  { slug: 'four-cousins-sweet-red', name: 'Four Cousins Sweet Red' },
  { slug: 'four-cousins-sweet-white', name: 'Four Cousins Sweet White' },
  { slug: 'sweet-kiss-natural-sweet-white', name: 'Sweet Kiss Natural Sweet White' },
  { slug: 'old-smuggler-blended-scotch-whisky', name: 'Old Smuggler Blended Scotch Whisky' },
  { slug: 'swartland-serengeti-sweet-white', name: 'Swartland Serengeti Sweet White' },
  { slug: 'voitis-single-malt-whiskey', name: 'Voitis Single Malt Whiskey' },
  { slug: 'laphroaig-10-years-old-original-cask-strength-finish', name: 'Laphroaig 10 Years Old Cask Strength Finish' },
  { slug: 'glenfiddich-grand-cru-23-year-old', name: 'Glenfiddich Grand Cru 23 Year Old' },
  { slug: 'pata-negra-reserva-tempranillo-2019', name: 'Pata Negra Reserva Tempranillo 2019' },
  { slug: 'maison-castel-ice-cuvee-blanche-demi-sec', name: 'Maison Castel Ice Cuvée Blanche Demi-Sec' },
  { slug: 'macallan-12-years-sherry-oak', name: 'Macallan 12 Years Sherry Oak' },
  { slug: 'sausage-tree-pure-irish-honey-badger', name: 'Sausage Tree Pure Irish Honey Badger' },
  { slug: 'veuve-clicquot-brut-champagne', name: 'Veuve Clicquot Brut Champagne' },
  { slug: 'maison-castel-muscat-medium-sweet', name: 'Maison Castel Muscat Medium Sweet' },
  { slug: 'johnnie-walker-red-label', name: 'Johnnie Walker Red Label' },
  { slug: 'hennessy-paradis', name: 'Hennessy Paradis' },
  { slug: 'santa-cristina-pinot-grigio-delle-venezie', name: 'Santa Cristina Pinot Grigio delle Venezie' },
  { slug: 'teeling-whiskey-30-years', name: 'Teeling Whiskey 30 Years' },
  { slug: 'poliphonia-family-blend-vinho-tinto', name: 'Poliphonia Family Blend Vinho Tinto' },
  { slug: 'lagavulin-16-year-old-43', name: 'Lagavulin 16 Year Old' },
  { slug: 'laphroaig-33-years-old-strong-characters', name: 'Laphroaig 33 Years Old Strong Characters' },
  { slug: 'thomas-barton-reserve-privee-medoc', name: 'Thomas Barton Reserve Privée Médoc' },
  { slug: 'hennessy-xo-la-carafe-high-energy', name: 'Hennessy XO La Carafe High Energy' },
  { slug: 'flirt-vodka-green-apple', name: 'Flirt Vodka Green Apple' },
  { slug: 'royal-salute-21-years', name: 'Royal Salute 21 Years' },
  { slug: 'glen-silvers-blended-scotch-whisky', name: 'Glen Silvers Blended Scotch Whisky' },
  { slug: 'smokehead-single-malt-whisky', name: 'Smokehead Single Malt Whisky' },
  { slug: 'santa-rita-120-reserva-especial-cabernet-sauvignon', name: 'Santa Rita 120 Reserva Especial Cabernet Sauvignon' },
  { slug: 'laphroaig-33-years', name: 'Laphroaig 33 Years' },
  { slug: 'glenfiddich-21-years-old', name: 'Glenfiddich 21 Years Old' },
  { slug: 'cooper-thief-2021', name: 'Cooper Thief 2021' },
  { slug: 'jura-island-12-years-old', name: 'Jura Island 12 Years Old' },
  { slug: 'sir-edwards-blended-scotch-whisky', name: 'Sir Edwards Blended Scotch Whisky' },
  { slug: 'ermelinda-vinho-tinto-sandstone-shiraz', name: 'Ermelinda Vinho Tinto Sandstone Shiraz' },
  { slug: 'highland-park-whisky-12-years', name: 'Highland Park Whisky 12 Years' },
  { slug: 'aultmore-22-double-cask-years-exceptional-cask-series', name: 'Aultmore 22 Double Cask Exceptional Cask Series' },
  { slug: 'ermelinda-vinho-tinto-dom-campos', name: 'Ermelinda Vinho Tinto Dom Campos' },
  { slug: 'maison-castel-ice-cuvee-demi-sec-rose', name: 'Maison Castel Ice Cuvée Demi-Sec Rosé' },
  { slug: 'lakes-salted-caramel-vodka', name: 'Lakes Salted Caramel Vodka' },
  { slug: 'torre-vinaria-d-abruzzo-pecorino-doc', name: "Torre Vinaria d'Abruzzo Pecorino DOC" },
  { slug: 'santa-rita-120-reserva-especial-red-blend', name: 'Santa Rita 120 Reserva Especial Red Blend' },
  { slug: 'olmeca-tequila-gold', name: 'Olmeca Tequila Gold' },
  { slug: 'festa-rose-wine', name: 'Festa Rosé Wine' },
  { slug: 'the-independent-prosecco-fantinel-brut', name: 'The Independent Prosecco Fantinel Brut' },
  { slug: 'drumshanbo-single-pot-still-irish-whiskey', name: 'Drumshanbo Single Pot Still Irish Whiskey' },
  { slug: 'monte-do-bar-o-vinho-tinto', name: 'Monte do Barão Vinho Tinto' },
  { slug: 'cazcabel-tequila-reposado', name: 'Cazcabel Tequila Reposado' },
  { slug: 'famille-perrin-la-vieille-ferme-ros', name: 'Famille Perrin La Vieille Ferme Rosé' },
  { slug: 'laphroaig-25-years-old', name: 'Laphroaig 25 Years Old' },
  { slug: 'moet-chandon-nectar-imperial-rose-champagne', name: 'Moët & Chandon Nectar Imperial Rosé' },
  { slug: 'louis-latour-chablis', name: 'Louis Latour Chablis' },
  { slug: 'dusse-xo', name: 'Düssé XO' },
  { slug: 'aberfeldy-23-years-double-cask', name: 'Aberfeldy 23 Years Double Cask' },
  { slug: 'santa-rita-120-reserva-especial-sauvignon-blanc', name: 'Santa Rita 120 Reserva Especial Sauvignon Blanc' },
  { slug: 'grace-omalley-blended-irish-whiskey', name: 'Grace O’Malley Blended Irish Whiskey' },
  { slug: 'independence-blended-irish-whiskey', name: 'Independence Blended Irish Whiskey' },
  { slug: 'santa-rita-120-reserva-especial-chardonnay', name: 'Santa Rita 120 Reserva Especial Chardonnay' },
  { slug: 'johnnie-walker-blue-label-ghost-rare', name: 'Johnnie Walker Blue Label Ghost & Rare' },
  { slug: 'santa-rita-tres-medallas-sauvignon-blanc', name: 'Santa Rita Tres Medallas Sauvignon Blanc' },
  { slug: 'the-glenlivet-12-years-double-oak', name: 'The Glenlivet 12 Years Double Oak' },
  { slug: 'kavalan-distillery-select-no-1', name: 'Kavalan Distillery Select No. 1' },
  { slug: 'sunblessed-vinho-tinto', name: 'Sunblessed Vinho Tinto' },
  { slug: 'reif-estate-winery-meritage-2020', name: 'Reif Estate Winery Meritage 2020' },
  { slug: 'glenfiddich-29-years-grand-yozakura', name: 'Glenfiddich 29 Years Grand Yozakura' },
  { slug: 'titos-handmade-vodka', name: "Tito's Handmade Vodka" },
  { slug: 'monte-dos-perdigoes-superior-vinho-tinto', name: 'Monte dos Perdigões Superior Vinho Tinto' },
  { slug: 'sunblessed-vinho-branco', name: 'Sunblessed Vinho Branco' },
  { slug: 'lheraud-loublie-xo', name: "Lheraud L'Oublié XO" },
  { slug: 'flirt-vodka-raspberry', name: 'Flirt Vodka Raspberry' },
  { slug: 'aultmore-15-years-marsala-wine-cask-collection', name: 'Aultmore 15 Years Marsala Wine Cask Collection' },
  { slug: 'el-espolon-tequila-blanco', name: 'El Espolòn Tequila Blanco' },
  { slug: 'west-cork-sherry-cask-finished', name: 'West Cork Sherry Cask Finished' },
  { slug: 'johnnie-walker-black-label', name: 'Johnnie Walker Black Label' },
  { slug: 'lagar-dos-perdig-es-reserva-alentejano-vinho-tinto', name: 'Lagar dos Perdigões Reserva Alentejano Vinho Tinto' },
  { slug: 'label-5-classic-black-whisky', name: 'Label 5 Classic Black Whisky' },
  { slug: 'glenfiddich-12-amontillado-sherry-cask-finish', name: 'Glenfiddich 12 Amontillado Sherry Cask Finish' },
  { slug: 'the-glenallachie-10-years-cask-strength-batch-11', name: 'The GlenAllachie 10 Years Cask Strength Batch 11' },
  { slug: 'the-macallan-night-on-earth-in-jerez', name: 'The Macallan Night On Earth In Jerez' },
  { slug: 'ciroc-vodka-imported', name: 'Cîroc Vodka Imported' },
  { slug: 'highland-park-18-years', name: 'Highland Park 18 Years' },
  { slug: 'ixsir-el-red-2016', name: 'Ixsir El Red 2016' },
  { slug: 'the-famous-grouse-smoky-black', name: 'The Famous Grouse Smoky Black' },
  { slug: 'glenfiddich-16-years-old', name: 'Glenfiddich 16 Years Old' },
  { slug: 'glenfiddich-grand-cortes-xxii', name: 'Glenfiddich Grand Cortes XXII' },
  { slug: 'santa-rita-120-reserva-malbec', name: 'Santa Rita 120 Reserva Malbec' },
  { slug: 'caperdonich-peated-25-years-old', name: 'Caperdonich Peated 25 Years Old' },
  { slug: 'cazcabel-tequila-honey', name: 'Cazcabel Tequila Honey' },
  { slug: 'the-observatory-20-years-old', name: 'The Observatory 20 Years Old' },
  { slug: 'aman-tequila-blanco', name: 'Aman Tequila Blanco' },
  { slug: 'nederburg-the-winemasters-pinotage', name: 'Nederburg The Winemasters Pinotage' },
  { slug: 'modaelsueno-watermelon-tequila', name: 'MODAelsueno Watermelon Tequila' },
  { slug: 'the-macallan-time-space', name: 'The Macallan Time Space' },
  { slug: 'jose-cuervo-silver-tequila', name: 'Jose Cuervo Silver Tequila' },
  { slug: 'aman-tequila-reposado', name: 'Aman Tequila Reposado' },
  { slug: 'flirt-vodka-chocolate', name: 'Flirt Vodka Chocolate' },
  { slug: 'skyy-vodka-plain', name: 'SKYY Vodka' },
  { slug: 'monte-perdigoes-alicante-bouschet-vinho-tinto', name: 'Monte Perdigões Alicante Bouschet Vinho Tinto' },
  { slug: 'inverroche-amber-gin', name: 'Inverroche Amber Gin' },
  { slug: 'aman-tequila-anejo', name: 'Aman Tequila Añejo' },
  { slug: 'skyy-vodka-infusion-citrus', name: 'SKYY Vodka Infusion Citrus' },
  { slug: 'the-macallan-m-decanter', name: 'The Macallan M Decanter' },
  { slug: 'wild-turkey-81', name: 'Wild Turkey 81' },
  { slug: 'bombay-sapphire', name: 'Bombay Sapphire Gin' },
  { slug: 'akashi-blended-whisky', name: 'Akashi Blended Whisky' },
  { slug: 'torbreck-barossa-valley-woodcutters-shiraz-2020', name: 'Torbreck Barossa Valley Woodcutters Shiraz 2020' },
  { slug: 'macleods-single-malt-lowland', name: 'MacLeod’s Single Malt Lowland' },
  { slug: 'san-felice-il-grigio-chianti-classico-riserva', name: 'San Felice Il Grigio Chianti Classico Riserva' },
  { slug: 'louis-jadot-combe-aux-jacques-beaujolais-villages', name: 'Louis Jadot Combe aux Jacques Beaujolais Villages' },
  { slug: 'jose-cuervo-reposado-tequila', name: 'Jose Cuervo Reposado Tequila' },
  { slug: 'drumshanbo-irish-galanta-reserva', name: 'Drumshanbo Irish Galanta Reserva' },
  { slug: 'cape-town-classic-dry-gin', name: 'Cape Town Classic Dry Gin' },
  { slug: 'cazcabel-tequila-coconut', name: 'Cazcabel Tequila Coconut' },
  { slug: 'rooderberg-cabernet-sauvignon', name: 'Rooiberg Cabernet Sauvignon' },
  { slug: 'famille-perrin-la-vieille-ferme-rouge', name: 'Famille Perrin La Vieille Ferme Rouge' },
  { slug: 'louis-latour-macon-villages-chameroy', name: 'Louis Latour Mâcon-Villages Chameroy' },
  { slug: 'riedel-extreme-restaurant-rose-champagne', name: 'Riedel Extreme Restaurant Rosé Champagne' },
  { slug: 'monte-do-barao-colheita-selectionada-vinho-tinto', name: 'Monte do Barão Colheita Selectionada Vinho Tinto' },
  { slug: 'the-glenallachie-18-years-46', name: 'The GlenAllachie 18 Years' },
  { slug: 'kavalan-concertmaster-port-cask-finish', name: 'Kavalan Concertmaster Port Cask Finish' },
  { slug: 'tanqueray-imported-gin-no-10', name: 'Tanqueray No. Ten Gin' },
  { slug: 'dewars-blended-whisky-12-years', name: 'Dewar’s Blended Whisky 12 Years' },
  { slug: 'torbreck-barossa-valley-the-struie-2020', name: 'Torbreck Barossa Valley The Struie 2020' },
  { slug: 'tamnavulin-speyside-port-cask-edition', name: 'Tamnavulin Speyside Port Cask Edition' },
  { slug: 'poliakov-premium-vodka', name: 'Poliakov Premium Vodka' },
  { slug: 'la-fiole-ch-teauneuf-du-pape', name: 'La Fiole Châteauneuf-du-Pape' },
  { slug: 'whitley-neill-blood-orange-gin', name: 'Whitley Neill Blood Orange Gin' },
  { slug: 'the-lakes-whiskymakers-edition-limited-release-infinity', name: 'The Lakes Whiskymaker’s Edition Infinity' },
  { slug: 'don-julio-blanco-tequila', name: 'Don Julio Blanco Tequila' },
  { slug: '818-tequila-a-ejo', name: '818 Tequila Añejo' },
  { slug: 'casa-maestri-tequila-reserva-blanco', name: 'Casa Maestri Tequila Reserva Blanco' },
  { slug: 'poliphonia-reserve-vinho-tinto', name: 'Poliphonia Reserve Vinho Tinto' },
  { slug: 'hennessy-vs-cognac', name: 'Hennessy VS Cognac' },
  { slug: 'the-yamazaki-single-malt-japanese-whisky-distillers-reserve', name: 'The Yamazaki Distiller’s Reserve' },
  { slug: 'monte-dos-perdig-es-viognier-gouveio-vinho-branco', name: 'Monte dos Perdigões Viognier Gouveio Vinho Branco' },
  { slug: 'terrazas-de-los-andes-reserva-malbec', name: 'Terrazas de los Andes Reserva Malbec' },
  { slug: 'the-glenallachie-11-years-premier-cru-classe-48', name: 'The GlenAllachie 11 Years Premier Cru Classé' },
  { slug: 'the-glenlivet-21-years-triple-cask-finish-first-fill', name: 'The Glenlivet 21 Years Triple Cask Finish' },
  { slug: 'veuve-cliquot-la-grande-dame', name: 'Veuve Clicquot La Grande Dame' },
  { slug: 'fantinel-tenuta-sant-helena-sauvignon-blanc', name: 'Fantinel Tenuta Sant’Helena Sauvignon Blanc' },
  { slug: 'el-padrino-de-mi-tierra-reposado', name: 'El Padrino de Mi Tierra Reposado' },
  { slug: 'chivas-regal-15-years', name: 'Chivas Regal 15 Years' },
  { slug: 'famille-perrin-miraval-studio-rose', name: 'Famille Perrin Miraval Studio Rosé' },
  { slug: 'drumshanbo-single-pot-still-irish-whiskey-marsala-cask', name: 'Drumshanbo Single Pot Still Marsala Cask' },
  { slug: 'kilchoman-px-sherry-cask-matured-2023', name: 'Kilchoman PX Sherry Cask Matured 2023' },
  { slug: 'tomatin-12-years-italian-barolo-cask-46', name: 'Tomatin 12 Years Italian Barolo Cask' },
  { slug: 'craigellachie-19-years', name: 'Craigellachie 19 Years' },
  { slug: '818-tequila-blanco', name: '818 Tequila Blanco' },
  { slug: 'the-singleton-12-years', name: 'The Singleton 12 Years' },
  { slug: 'vivir-tequila-reposado', name: 'Vivir Tequila Reposado' },
  { slug: 'highland-park-15-years-old', name: 'Highland Park 15 Years Old' },
  { slug: 'aman-tequila-anejo-cristalino', name: 'Aman Tequila Añejo Cristalino' },
  { slug: 'el-espolon-tequila-reposado', name: 'El Espolòn Tequila Reposado' },
  { slug: '818-eight-reserve-anejo-tequila', name: '818 Eight Reserve Añejo Tequila' },
  { slug: 'baron-richman-white', name: 'Baron Richman White Wine' },
  { slug: 'declan-de-espana-sweet-white', name: 'Declan De España Sweet White Wine' },
  { slug: 'declan-moscato-pear-honeysuckle', name: 'Declan Moscato Pear & Honeysuckle' },
  { slug: 'chateau-vartely-muscat-white', name: 'Chateau Vartely Muscat White Wine' },
  { slug: 'chateau-vartely-muscat-rose', name: 'Chateau Vartely Muscat Rosé' },
  { slug: 'cricova-pastoral-sweet-red', name: 'Cricova Pastoral Sweet Red Wine' },
  { slug: 'darling-cellar-sweet-red', name: 'Darling Cellar Sweet Red Wine' },
  { slug: 'amabile-di-rosa-sweet-red', name: 'Amabile Di Rosa Sweet Red Wine' },
  { slug: 'isolabella-della-croce-maria-teresa-barbera-d-asti', name: 'Isolabella Della Croce Maria Teresa Barbera d’Asti' },
  { slug: 'caymus-vineyards-california-cabernet-sauvignon-2023', name: 'Caymus California Cabernet Sauvignon 2023' },
  { slug: 'caymus-vineyards-special-selection-cabernet-sauvignon-2020', name: 'Caymus Special Selection Cabernet Sauvignon 2020' },
  { slug: 'caymus-honor-flight-napa-valley-cabernet-sauvignon-2019', name: 'Caymus Honor Flight Napa Valley Cabernet Sauvignon 2019' },
  { slug: 'chateau-hostens-picant-cuvee-d-exception-lucullus-2016', name: 'Chateau Hostens-Picant Cuvée d’Exception Lucullus 2016' },
  { slug: 'cloudy-bay-pinot-noir-2018', name: 'Cloudy Bay Pinot Noir 2018' },
  { slug: 'chateau-vartely-taraboste-pinot-noir', name: 'Chateau Vartely Taraboste Pinot Noir' },
  { slug: 'cederberg-bukketraube', name: 'Cederberg Bukketraube' },
  { slug: 'deau-pineau-des-charentes-blanc', name: 'Deau Pineau des Charentes Blanc' },
  { slug: '19-crimes-the-uprising-chardonnay', name: '19 Crimes The Uprising Chardonnay' },
  { slug: '19-crimes-cabernet-sauvignon-2021', name: '19 Crimes Cabernet Sauvignon 2021' },
  { slug: '19-crimes-the-banished', name: '19 Crimes The Banished Red Wine 2021' },
  { slug: '19-crimes-the-uprising-red', name: '19 Crimes The Uprising Red Wine' },
  { slug: 'casa-dorada-sparkling-wine-non-alcoholic', name: 'Casa Dorada Non-Alcoholic Sparkling Wine' },
  { slug: 'cantine-maschio-alcohol-free', name: 'Cantine Maschio Alcohol-Free White Wine' },
  { slug: 'eisberg-cabernet-sauvignon-alcohol-free', name: 'Eisberg Alcohol-Free Cabernet Sauvignon' },
  { slug: 'eisberg-merlot-alcohol-free', name: 'Eisberg Alcohol-Free Merlot' },
  { slug: 'blue-nun-silver-non-alcoholic', name: 'Blue Nun Silver Non-Alcoholic White Wine' },
  { slug: 'monte-do-barao-reserva-vinho-tinto', name: 'Monte do Barao Reserva Vinho Tinto' },
  { slug: 'monte-dos-perdigoes-vinhas-velhas-tinto', name: 'Monte dos Perdigões Vinhas Velhas Tinto' },
  { slug: 'monte-dos-perdigoes-colheita-selectionada-vinho-tinto', name: 'Monte dos Perdigões Colheita Selectionada' },
  { slug: 'lagar-dos-perdig-es-colheita-vinho-branco', name: 'Lagar dos Perdigões Colheita Vinho Branco' },
  { slug: 'lagar-dos-perdig-es-colheita-vinho-tinto', name: 'Lagar dos Perdigões Colheita Vinho Tinto' },
  { slug: 'cantina-settecani-lambrusco-grasparossa-di-castelvetro-secco', name: 'Cantina Settecani Lambrusco Grasparossa Secco' },
  { slug: 'leopard-cape-lookout-mountain-white-2023', name: 'Leopard Cape Lookout Mountain White 2023' },
  { slug: 'maison-castel-cabernet-sauvignon-2020', name: 'Maison Castel Cabernet Sauvignon 2020' },
  { slug: 'nederburg-the-winemasters-merlot', name: 'Nederburg The Winemasters Merlot' },
  { slug: 'nederburg-the-winemasters-shiraz', name: 'Nederburg The Winemasters Shiraz' },
  { slug: 'richland-merlot', name: 'Richland Merlot Red Wine' },
  { slug: 'riunite-moscato-white-wine', name: 'Riunite Moscato White Wine' },
  { slug: 'robertson-chapel-sweet-red-wine', name: 'Robertson Chapel Sweet Red Wine' },
  { slug: 'robertson-natural-sweet-white-wine', name: 'Robertson Natural Sweet White Wine' },
  { slug: 'antinori-tignanello-toscana-2020', name: 'Antinori Tignanello Toscana 2020' },
  { slug: 'santa-cristina-vermentino-toscana', name: 'Santa Cristina Vermentino Toscana' },
  { slug: 'santa-rita-3-tres-medallas-sweet-red', name: 'Santa Rita Tres Medallas Sweet Red Wine' },
  { slug: 'saracco-moscato-d-asti', name: 'Saracco Moscato d’Asti' },
  { slug: 'siglo-tinto-rioja', name: 'Siglo Tinto Rioja' },
  { slug: 'silk-and-spice-red-blend', name: 'Silk And Spice Red Blend' },
  { slug: 'ermelinda-freitas-moscatel-de-set-bal', name: 'Ermelinda Freitas Moscatel' },
  { slug: 'ermelinda-vinho-branco-espumante-meio-seco', name: 'Ermelinda Vinho Branco Espumante Meio Seco' },
  { slug: 'dona-ermelinda-vinho-branco-palmela', name: 'Dona Ermelinda Vinho Branco Palmela' },
  { slug: 'dona-ermelinda-vinho-tinto-palmela', name: 'Dona Ermelinda Vinho Tinto Palmela' },
  { slug: 'escudo-rojo-red-luminous', name: 'Escudo Rojo Red Luminous' },
  { slug: 'expression-sweet-red', name: 'Expression Sweet Red Wine' },
  { slug: 'fairview-spice-route-chakalaka', name: 'Fairview Spice Route Chakalaka' },
  { slug: 'famille-perrin-la-vieille-ferme-blanc', name: 'Famille Perrin La Vieille Ferme Blanc' },
  { slug: 'fantinel-sun-goddess-pinot-grigio-rose', name: 'Fantinel Sun Goddess Pinot Grigio Rosé' },
  { slug: 'fantinel-sun-goddess-prosecco-brut', name: 'Fantinel Sun Goddess Prosecco Brut' },
  { slug: 'festa-sweet-red-wine', name: 'Festa Sweet Red Wine' },
  { slug: 'tenuta-sant-helena-refosco', name: "Tenuta Sant'Helena Refosco" },
  { slug: 'terrazas-de-los-andes-torrontes', name: 'Terrazas de los Andes Torrontes' },
  { slug: 'thomas-barton-reserve-graves-blanc-2020', name: 'Thomas Barton Reserve Graves Blanc 2020' },
  { slug: 'hennessy-vsop-cognac', name: 'Hennessy VSOP Cognac' },
  { slug: 'luc-belaire-rare-rose', name: 'Luc Belaire Rare Rosé' },
  { slug: 'martini-brut-prosecco', name: 'Martini Brut Prosecco' },
  { slug: 'martini-prosecco-doc', name: 'Martini Prosecco DOC' },
  { slug: 'menage-a-trois-red-blend', name: 'Menage a Trois Red Blend' },
  { slug: 'bayab-orange-marula-gin', name: 'Bayab Orange & Marula Gin' },
  { slug: 'bayab-rose-water-gin', name: 'Bayab Rose Water Gin' },
  { slug: 'cape-town-pink-lady-gin', name: 'Cape Town Pink Lady Gin' },
  { slug: 'drumshanbo-gunpowder-irish-gin-california-orange', name: 'Drumshanbo Gunpowder Irish Gin California Orange' },
  { slug: 'drumshanbo-irish-gin-ceramic', name: 'Drumshanbo Irish Gin Ceramic' },
  { slug: 'gordon-dry-gin-moringa-citrus', name: 'Gordon Dry Gin Moringa Citrus' },
  { slug: 'gordon-london-dry-gin', name: 'Gordon London Dry Gin' },
  { slug: 'gordons-sunset-original', name: "Gordon's Sunset Original Gin" },
  { slug: 'hendricks-gin', name: 'Hendricks Gin' },
  { slug: 'inverroche-verdant-gin', name: 'Inverroche Verdant Gin' },
  { slug: 'victoria-s-stag-strawberry-gin', name: "Victoria's Stag Strawberry Gin" },
  { slug: 'agavales-gold-tequila', name: 'Agavales Gold Tequila' },
  { slug: 'don-julio-a-ejo-1942', name: 'Don Julio Añejo 1942' },
  { slug: 'casamigos-tequila-blanco', name: 'Casamigos Tequila Blanco' },
  { slug: 'casamigos-tequila-anejo', name: 'Casamigos Tequila Añejo' },
  { slug: '818-tequila-reposado', name: '818 Tequila Reposado' },
  { slug: 'aman-tequila-rosa-blanco', name: 'Aman Tequila Rosa Blanco' },
  { slug: 'cazcabel-tequila-anejo', name: 'Cazcabel Tequila Añejo' },
  { slug: 'cazcabel-tequila-coffee', name: 'Cazcabel Tequila Coffee Liqueur' },
  { slug: 'el-padrino-de-mi-tierra-anejo', name: 'El Padrino de Mi Tierra Añejo' },
  { slug: 'el-padrino-de-mi-tierra-chocolate-crema', name: 'El Padrino de Mi Tierra Chocolate Crema' },
  { slug: 'el-padrino-de-mi-tierra-crema-original', name: 'El Padrino de Mi Tierra Crema Original' },
  { slug: 'absolut-citron', name: 'Absolut Citron' },
  { slug: 'absolut-mandrin', name: 'Absolut Mandrin' },
  { slug: 'absolut-raspberry', name: 'Absolut Raspberry Vodka' },
  { slug: 'absolut-vodka', name: 'Absolut Vodka' },
  { slug: 'belvedere-vodka', name: 'Belvedere Vodka' },
  { slug: 'ciroc-vodka-red-berry', name: 'Cîroc Red Berry Vodka' },
  { slug: 'grey-goose-lorange', name: "Grey Goose L'Orange" },
  { slug: 'grey-goose-vodka', name: 'Grey Goose Vodka' },
  { slug: 'bruichladdich-the-classic-laddie', name: 'Bruichladdich The Classic Laddie' },
  { slug: 'buffalo-trace-kentucky-whisky', name: 'Buffalo Trace Kentucky Whisky' },
  { slug: 'bushmills-33-years-causeway-collection', name: 'Bushmills 33 Years Causeway Collection' },
  { slug: 'bushmills-black-bush-whiskey', name: 'Bushmills Black Bush Irish Whiskey' },
  { slug: 'bushmills-original-10-years-whiskey', name: 'Bushmills Original 10 Years Irish Whiskey' },
  { slug: 'bushmills-signature-irish-whiskey', name: 'Bushmills Signature Irish Whiskey' },
  { slug: 'caperdonich-peated-21-years', name: 'Caperdonich Peated 21 Years Single Malt' },
  { slug: 'chivas-regal-12-years-old', name: 'Chivas Regal 12 Years Old' },
  { slug: 'chivas-regal-18-years', name: 'Chivas Regal 18 Years Old' },
  { slug: 'drumshanbo-irish-whiskey-pinot-noir-cask', name: 'Drumshanbo Irish Whiskey Pinot Noir Cask' },
  { slug: 'fercullen-single-malt-irish-whiskey', name: 'Fercullen Single Malt Irish Whiskey' },
  { slug: 'fercullen-small-batch-irish-whiskey', name: 'Fercullen Small Batch Irish Whiskey' },
  { slug: 'glen-deveron-28-years', name: 'Glen Deveron 28 Years Single Malt Scotch' },
  { slug: 'glenfiddich-12-years-old-american-oak', name: 'Glenfiddich 12 Years Old American Oak' },
  { slug: 'glengoyne-single-malt-whisky-12-years', name: 'Glengoyne 12 Years Single Malt Scotch' },
  { slug: 'glenmorangie-bond-house-1997', name: 'Glenmorangie Bond House 1997' },
  { slug: 'glenmorangie-the-original-10-years', name: 'Glenmorangie The Original 10 Years' },
  { slug: 'glenmorangie-quinta-ruban-14-years-old', name: 'Glenmorangie Quinta Ruban 14 Years' },
  { slug: 'grangestone-bourbon-cask-finish-whisky', name: 'Grangestone Bourbon Cask Finish Whisky' },
  { slug: 'green-spot-triple-distilled-irish-whiskey', name: 'Green Spot Triple Distilled Irish Whiskey' },
  { slug: 'highland-park-30-years', name: 'Highland Park 30 Years Single Malt Scotch' },
  { slug: 'hyde-single-grain-bourbon-cask-1916', name: 'Hyde Single Grain Bourbon Cask 1916' },
  { slug: 'hyde-single-malt-port-cask', name: 'Hyde Single Malt Port Cask Irish Whiskey' },
  { slug: 'hyde-single-malt-rum-cask-1922', name: 'Hyde Single Malt Rum Cask 1922' },
  { slug: 'jack-daniels-honey-1-rocks-glass', name: 'Jack Daniels Honey Whiskey & Rocks Glass' },
  { slug: 'jack-daniel-s-old-no-7', name: "Jack Daniel's Old No. 7 Tennessee Whiskey" },
  { slug: 'jack-daniels-old-no-7-with-2-glass-cups', name: 'Jack Daniels Old No. 7 with 2 Glass Cups' },
  { slug: 'jack-daniel-s-tennessee-fire', name: 'Jack Daniels Tennessee Fire' },
  { slug: 'james-king-blended-scotch-whiskey', name: 'James King Blended Scotch Whiskey' },
  { slug: 'johnnie-walker-double-black', name: 'Johnnie Walker Double Black' },
  { slug: 'johnnie-walker-gold-label', name: 'Johnnie Walker Gold Label' },
  { slug: 'johnnie-walker-green-label-15-years', name: 'Johnnie Walker Green Label 15 Years' },
  { slug: 'jura-island-10-years', name: 'Jura Island 10 Years Single Malt Scotch' },
  { slug: 'jura-island-journey', name: 'Jura Island Journey 18 Year Old' },
  { slug: 'label-5-18-years-old-blended-scotch-whisky-gift-box', name: 'Label 5 18 Years Old Blended Scotch Gift Box' },
  { slug: 'label-5-bourbon-barrel-whisky', name: 'Label 5 Bourbon Barrel Whisky' },
  { slug: 'macleods-single-malt-highland-whisky', name: "Macleod's Single Malt Highland Whisky" },
  { slug: 'monkey-shoulder-blended-malt-scotch', name: 'Monkey Shoulder Blended Malt Scotch Whisky' },
  { slug: 'scots-hills-blended-scotch-whisky', name: 'Scots Hills Blended Scotch Whisky' },
  { slug: 'teeling-whisky-small-batch', name: 'Teeling Small Batch Irish Whiskey' },
  { slug: 'tenjaku-sherry-cask-japanese-whisky', name: 'Tenjaku Sherry Cask Japanese Whisky' },
  { slug: 'tenjaku-whisky', name: 'Tenjaku Japanese Whisky' },
  { slug: 'the-glenlivet-15-years-single-malt-scotch', name: 'The Glenlivet 15 Years Single Malt Scotch' },
  { slug: 'the-macallan-hong-kong', name: 'The Macallan Hong Kong Premium Single Malt' },
  { slug: 'the-singleton-15-years', name: 'The Singleton 15 Years Single Malt Scotch' },
  { slug: 'william-lawson-blended-scotch-whisky', name: 'William Lawson Blended Scotch Whisky' },
  { slug: 'casamigos-tequila-reposado', name: 'Casamigos Tequila Reposado' },
  { slug: 'caymus-cabernet-sauvignon-2023', name: 'Caymus Cabernet Sauvignon 2023' },
  { slug: 'don-julio-reposado-tequila', name: 'Don Julio Reposado Tequila' },
  { slug: 'dona-celia-tequila-anejo', name: 'Dona Celia Tequila Añejo' },
  { slug: 'emblem-cabernet-sauvignon', name: 'Emblem Cabernet Sauvignon' },
  { slug: 'frank-phelan-2016-saint-estephe-rouge', name: 'Frank Phelan 2016 Saint-Estèphe Rouge' },
  { slug: 'glencadam-15-years', name: 'Glencadam 15 Years Highland Scotch' },
  { slug: 'glenfiddich-26-year-old', name: 'Glenfiddich 26 Year Old' },
  { slug: 'glenmorangie-18-years-old-single-malt-scotch-whisky-gift-pack', name: 'Glenmorangie 18 Single Malt Scotch Whisky' },
  { slug: 'glenmorangie-the-signet-extra-matured-single-malt-scotch-whisky-gift-pack', name: 'Glenmorangie The Signet Single Malt Scotch' },
  { slug: 'gold-bar-blended-whisky', name: 'Gold Bar Blended Whisky' },
  { slug: 'green-river-rye-whiskey', name: 'Green River Rye Whiskey' },
  { slug: 'hennessy-xo-cognac-gift-pack', name: 'Hennessy XO Cognac Gift Pack' },
  { slug: 'hennessy-xo-kim-jones-version', name: 'Hennessy XO Kim Jones' },
  { slug: 'henri-lurton-baron-de-brane-margaux', name: 'Henri Lurton Baron de Brane Margaux' },
  { slug: 'hibiki-suntory-whisky-japanese-harmony', name: 'Hibiki Suntory Japanese Harmony Whisky' },
  { slug: 'high-west-double-rye-whiskey', name: 'High West Double Rye Whiskey' },
  { slug: 'highland-park-21-years', name: 'Highland Park 21 Years' },
  { slug: 'ixsir-el-white-2019', name: 'Ixsir El White 2019' },
  { slug: 'jack-daniels-sinatra-select', name: 'Jack Daniels Sinatra Select' },
  { slug: 'johnnie-walker-18-years-platinum-label', name: 'Johnnie Walker 18 Platinum' },
  { slug: 'johnnie-walker-blue-label-whisky', name: 'Johnnie Walker Blue Label Whisky' },
  { slug: 'jura-island-18-years', name: 'Jura Island 18 Years' },
  { slug: 'kanonkop-cabernet-sauvignon-2017', name: 'Kanonkop Cabernet Sauvignon 2017' },
  { slug: 'kavalan-classic-single-malt-whisky-40', name: 'Kavalan Classic Single Malt Whisky' },
  { slug: 'kilchoman-batch-sauternes-cask-2024-release-50', name: 'Kilchoman Batch Sauternes Cask 2024' },
  { slug: 'kilchoman-batch-strength-57', name: 'Kilchoman Batch Strength 57%' },
  { slug: 'kilchoman-loch-gorm-sherry-cask-matured-2024-edition', name: 'Kilchoman Loch Gorm 2024' },
  { slug: 'kilchoman-machir-bay', name: 'Kilchoman Machir Bay' },
  { slug: 'kilchoman-sanaig', name: 'Kilchoman Sanaig' },
  { slug: 'knob-creek-kentucky-straight-rye-whiskey', name: 'Knob Creek Kentucky Straight Rye Whiskey' },
  { slug: 'kopke-20-years-old-port-wine', name: 'Kopke 20 Years Old Tawny Port' },
  { slug: 'la-sirene-de-giscours-margaux', name: 'La Sirène de Giscours Margaux 2017' },
  { slug: 'laphroaig-10-years-old-40', name: 'Laphroaig 10 Years Old 40%' },
  { slug: 'le-petit-ducru-de-ducru-beaucaillou-2020', name: 'Le Petit Ducru 2020 Saint-Julien' },
  { slug: 'lheraud-cognac-vsop', name: 'Lheraud Cognac VSOP' },
  { slug: 'modaelsueno-pineapple-tequila', name: 'MODAelsueno Pineapple Tequila' },
  { slug: 'modaelsueno-pink-grapefruit-tequila', name: 'MODAelsueno Pink Grapefruit Tequila' },
  { slug: 'mijenta-tequila-cristalino', name: 'Mijenta Tequila Cristalino' },
  { slug: 'mijenta-tequila-reposado', name: 'Mijenta Tequila Reposado' },
  { slug: 'moet-chandon-rose-imperial-love-champagne', name: 'Moët & Chandon Rosé Imperial Love' },
  { slug: 'oreno-toscana', name: 'Oreno Toscana Premium Red Wine' },
  { slug: 'padre-azul-super-premium-tequila-reposado', name: 'Padre Azul Super Premium Tequila Reposado' },
  { slug: 'pinhook-kentucky-straight-rye-whiskey', name: 'Pinhook Kentucky Straight Rye Whiskey' },
  { slug: 'pol-roger-reserve-brut-champagne', name: 'Pol Roger Reserve Brut Champagne' },
  { slug: 'pol-roger-rich-demi-sec-champagne', name: 'Pol Roger Rich Demi-Sec Champagne' },
  { slug: 'remy-martin-1738', name: 'Rémy Martin 1738' },
  { slug: 'ruinart-champagne-blanc-de-blancs', name: 'Ruinart Blanc de Blancs Champagne' },
  { slug: 'ruinart-champagne-brut', name: 'Ruinart Champagne Brut' },
  { slug: 'ruinart-rose-nv-champagne', name: 'Ruinart Rosé NV Champagne' },
  { slug: 'smooth-ambler-contradiction-rye-whiskey', name: 'Smooth Ambler Contradiction Rye Whiskey' },
  { slug: 'the-balvenie-rum-cask-finish-14-years', name: 'The Balvenie Rum Cask Finish 14 Years' },
  { slug: 'the-glenallachie-15-years-46', name: 'The GlenAllachie 15 Years' },
  { slug: 'hakushu-12-year-single-malt-japanese-whiskey', name: 'Hakushu 12 Year Single Malt' },
  { slug: 'the-hakushu-single-malt-japanese-whisky-distillers-reserve', name: 'Hakushu Distiller’s Reserve' },
  { slug: 'the-lakes-whiskymakers-edition-limited-release-iris', name: 'The Lakes Iris Limited Edition Whisky' },
  { slug: 'the-macallan-sherry-oak-cask-18-years', name: 'The Macallan Sherry Oak Cask 18 Years' },
  { slug: 'the-observatory-25-years-single-grain-whisky', name: 'The Observatory 25 Years Single Grain' },
] as const;

const ADDITIONAL_SITEGURU_PRODUCT_SLUGS = [
  'the-singleton-of-dufftown-18-years','veuve-clicquot-rich-rose','veuve-clicquot-rose-champagne','veuve-cliquot-champagne-rich','aberfeldy-single-malt-21-years','akashi-blended-sherry-oak-finish','akashi-meisei-blended-whisky','american-honey-sting','ardbeg-10-years','ardbeg-25-years','ardbeg-uigeadail-single-malt','ardbeg-wee-beastie-5-years','ardbeg-heavy-vapours','armorik-classic-whisky','armorik-sherry-cask-whisky','aultmore-25-years-first-fill-sherry-cask-finish','aultmore-speyside-single-malt-12-years-46','aultmore-speyside-single-malt-18-years-46','bains-cape-mountain-whiskey-single-grain','ballantines-blended-scotch-whisky','benriach-12-years-old-the-twelve','benriach-30-years-1898','black-white-blended-scotch-whisky','bruichladdich-octomore','lachateau-vouvray-2020','rich-lady-sweet-red','maison-de-vin-cabernet-sauvignon','gai-a-agiorgitiko-2023','la-roncaia-refosco-2012','marani-napareuli-2018','la-camensarde-beaujolais-villages','reif-estate-winery-chardonnay','the-hanging-man-kerner-2023','reif-estate-winery-gewurztraminer-2020','reif-estate-winery-sauvignon-blanc-2021','reif-estate-winery-unoaked-chardonnay','reif-estate-winery-kiln-dried-cabernet','penfolds-max-chardonnay','reif-estate-winery-pinot-noir-2020','sandeman-fine-white-porto','penfolds-max-shiraz-cabernet','kopke-dry-white-porto','kopke-fine-ruby-porto','kopke-fine-tawny-porto','kopke-fine-white-porto','kopke-lbv-2018-porto','kopke-lagrima-white-porto','kopke-40-years-old-port-wine','kopke-30-years-old-port-wine','angel-non-alcoholic-sparkling-red-grape-wine','reif-estate-vinea-liqueur','martinellis-apple-cider','penfolds-grandfather-rare-tawny-20-years','laphroaig-34-year-old-the-ian-hunter-story-book-5-enduring-spirit','tapada-do-barao-colheita-selectionada-vinho-tinto','tapada-do-barao-colheita-selectionada-vinho-branco','monte-do-barao-vinho-branco','miral-syrah-terre-siciliane-igp','miral-nero-d-avola-organic-sicilia-doc-2024','miral-chardonnay-terre-siciliane-igp-bio-2025','lamonthe-parrot-sweet-white','leopards-leap-merlot-2021','leopards-leap-sauvignon-blanc-2023','leopards-leap-unwooded-chardonnay','les-dauphins-c-te-du-rh-ne-reserve','luccianus-amphore-lussac-saint-milion','martini-bianco','martini-extra-dry','martini-fiero','mimi-kiss-sweet-red','moillard-chablis-coquillage','moillard-pouilly-fuisse-sous-la-grotte','nederburg-premiere-cuvee-brut','nederburg-sauvignon-blanc-2021','nederburg-winemasters-edelrood-cabernet-sauvignon-merlot','pearly-bay-celebration-sparkling-white','penfolds-club-reserve-classic-tawny','prosper-maufoux-bourgogne-hautes-c-tes-de-nuits','reif-estate-winery-merlot-2019','riunite-lambrusco','robertson-natural-sweet-red','robertson-winery-chapel-white','rubis-chocolate-velvet-wine','sandeman-fine-ruby-porto','sandeman-founders-reserve-ruby-port','sandeman-imperial-fine-tawny-porto','santa-rita-tres-medallas-sweet-white','santa-rita-medalla-real-reserva-sauvignon-blanc','santa-rita-real-medallas-gold-medal-cabernet-sauvignon-2018','saxenburg-private-collection-sauvignon-blanc','scavi-ray-rosso-prestigio-al-cioccolata','siglo-tempranillo-rioja','springfield-the-work-of-time-blend','springfield-wild-yeast-chardonnay-2021','terrazas-de-los-andes-chardonnay','thomas-barton-bordeaux','thomas-barton-reserve-margaux','thomas-barton-reserve-medoc','thomas-barton-saint-emilion-2023','torbreck-barossa-valley-the-steading-2018','luc-belaire-rare-luxe','luc-belaire-rare-luxe-fantome','martinellis-sparkling-apple-non-alcoholic','martini-asti','martini-ros','roaring-meg-pinot-noir-2023','whispering-angel-cotes-de-provence-rose','drumshanbo-irish-sardinian-citrus','the-botanist-islay-dry-gin','whitley-neill-pink-grapefruit-gin','olmeca-blanco','patr-n-a-ejo-tequila','patron-reposado-tequila','patron-silver-tequila','vivir-tequila-blanco','volcan-de-mi-tierra-blanco-tequila','flirt-vodka-plain','skyy-vodka-infusion-passion-fruit','skyy-vodka-infusion-pineapple','smirnoff-vodka-red','dalmore-aged-12-years','dalmore-king-alexander-iii-highland-single-malt','grants-12-year-old-blended-scotch-whisky','grants-triple-wood','highland-legend-blended-malt','jack-daniels-honey','jack-daniels-single-barrel','king-charles-blended-scotch-whiskey','laphroaig-30-years','ledaig-18-years-isle-of-mull','the-macallan-m-copper-2023','the-macallan-sherry-oak-30-years','macleod-s-single-malt-speyside','mc-queen-violet-fog-handcrafted-gin','old-pulteney-12-years','old-pulteney-15-year-old-46','sheep-dog-peanut-butter','southern-comfort-original','talisker-30-years','taylors-1966-single-harvest-port','teeling-whiskey-32-years','teeling-whiskey-single-grain','teeling-whisky-blackpitt','teeling-whisky-single-malt','the-balvenie-doublewood-12-years','the-glenallachie-35-year','the-glenlivet-founders-reserve-single-malt','the-independence-single-malt-irish-whiskey','the-irishman-the-harvest-irish-whiskey','the-kurayoshi-japanese-pure-malt-12-years',
] as const;

function productLabel(slug: string): string {
  return slug.replace(/-/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export const OPPORTUNITY_PRODUCTS = [
  ...CORE_OPPORTUNITY_PRODUCTS,
  ...ADDITIONAL_SITEGURU_PRODUCT_SLUGS.map((slug) => ({ slug, name: productLabel(slug) })),
];

export const BRAND_OPPORTUNITY_SLUGS: Record<string, readonly string[]> = {
  glenfiddich: ['glenfiddich-12-years-old', 'glenfiddich-15-years-old', 'glenfiddich-18-years-old'],
  moet: ['moet-chandon-ice-imperial-champagne', 'moet-chandon-nectar-imperial-blanc-champagne', 'moet-chandon-rose-imperial-champagne'],
  'moet-chandon': ['moet-chandon-ice-imperial-champagne', 'moet-chandon-nectar-imperial-blanc-champagne', 'moet-chandon-rose-imperial-champagne'],
  macallan: ['the-macallan-12-years-double-cask', 'the-macallan-whisky-15-years-double-cask', 'the-macallan-double-cask-18-years'],
  jameson: ['jameson-black-barrel', 'jameson-stout-edition-irish-whiskey'],
  martell: ['martell-blue-swift', 'martell-vs', 'martell-chanteloup-xxo', 'martell-xo'],
  'four-cousins': ['four-cousins-cabernet-sauvignon-2024', 'four-cousins-directors-reserve-merlot-2021', 'four-cousins-dry-rose', 'four-cousins-merlot-2024', 'four-cousins-pinotage-2023', 'four-cousins-sauvignon-blanc', 'four-cousins-sweet-red', 'four-cousins-sweet-white'],
  'sweet-kiss': ['sweet-kiss-natural-sweet-white'],
};

/** A small editorial link module; the full catalogue remains in the sitemap. */
export default function OpportunityProductLinks({ includeSlugs, limit = 8 }: { includeSlugs?: readonly string[]; limit?: number }) {
  const matchingProducts = includeSlugs
    ? OPPORTUNITY_PRODUCTS.filter((product) => includeSlugs.includes(product.slug))
    : OPPORTUNITY_PRODUCTS;
  const products = matchingProducts.slice(0, limit);
  if (products.length === 0) return null;
  return (
    <section className="border-t border-stone-200 bg-[#fbf8f3] px-4 py-10" aria-labelledby="opportunity-products-heading">
      <div className="mx-auto max-w-6xl">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.24em] text-[#9b5a4e]">From the harbour</p>
            <h2 id="opportunity-products-heading" className="mt-1 text-2xl font-bold tracking-tight text-stone-900">Popular bottles to explore</h2>
            <p className="mt-2 max-w-xl text-sm text-stone-600">A considered shortlist of bottles customers are searching for now.</p>
          </div>
          <Link href="/shop" className="text-sm font-bold text-[#7C1D1D] underline-offset-4 hover:underline">Browse the full shop →</Link>
        </div>
        <nav aria-label="Popular product links" className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {products.map((product, index) => (
            <Link key={product.slug} href={`/product/${product.slug}`} className="group rounded-2xl border border-stone-200/80 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-[#b87968] hover:shadow-md motion-reduce:transition-none motion-reduce:hover:translate-y-0">
              <span className="text-[10px] font-bold uppercase tracking-[0.18em] text-stone-400">0{index + 1}</span>
              <span className="mt-3 block text-sm font-bold leading-5 text-stone-900 group-hover:text-[#7C1D1D]">{product.name}</span>
              <span className="mt-3 block text-xs font-semibold text-[#9b5a4e]">View bottle <span aria-hidden="true">↗</span></span>
            </Link>
          ))}
        </nav>
      </div>
    </section>
  );
}
