export type Category =
  | 'all'
  | 'Wine Guide'
  | 'Spirits Guide'
  | 'Beer Guide'
  | 'Recipes'
  | 'Entertaining'
  | 'Lifestyle';

export interface ContentBlock {
  type: 'p' | 'h2' | 'h3' | 'ul' | 'ol' | 'quote' | 'tip';
  text?: string;
  items?: string[];
}

export interface Post {
  id: number;
  title: string;
  excerpt: string;
  category: Exclude<Category, 'all'>;
  date: string;
  isoDate: string;
  readTime: string;
  image: string;
  slug: string;
  featured?: boolean;
  tags: string[];
  author: { name: string; role: string; bio: string };
  content: ContentBlock[];
}

export const POSTS: Post[] = [
  {
    id: 1,
    title: 'Top 10 Wines for Beginners in Nigeria',
    excerpt: "Starting your wine journey? We've rounded up the most approachable, crowd-pleasing bottles available right now — all at sensible prices.",
    category: 'Wine Guide',
    date: 'May 5, 2026',
    isoDate: '2026-05-05',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200&q=80',
    slug: 'top-10-wines-for-beginners',
    featured: true,
    tags: ['Wine', 'Beginners', 'Guide'],
    author: { name: 'Adaeze Nwosu', role: 'Wine Sommelier', bio: 'A certified sommelier with seven years of experience curating wine lists for Lagos top restaurants. Adaeze trained at the Wine & Spirit Education Trust and believes great wine is for everyone.' },
    content: [
      { type: 'p', text: "Wine can feel intimidating — but it doesn't have to be. The key is starting with styles that are fruit-forward, low in tannins, and widely available in Nigeria. Here are our top picks for anyone just getting started." },
      { type: 'h2', text: '1. Jacob\'s Creek Classic Shiraz (Australia)' },
      { type: 'p', text: 'Plummy, smooth, and very easy to enjoy on its own or with grilled meats. One of the most popular entry-level reds in Nigeria.' },
      { type: 'h2', text: '2. Barefoot Pinot Grigio (USA)' },
      { type: 'p', text: 'Crisp, light, and refreshing. Great for warm Lagos evenings. Pairs beautifully with seafood and light pasta.' },
      { type: 'h2', text: '3. Mateus Rosé (Portugal)' },
      { type: 'p', text: 'A Nigerian favourite for decades. Semi-sweet, lightly sparkling, and unmistakably fun. The ideal starter rosé.' },
      { type: 'h2', text: '4. Santa Rita 120 Sauvignon Blanc (Chile)' },
      { type: 'p', text: 'Zesty citrus and tropical fruit. Sauvignon Blanc is one of the most food-friendly whites — and this Chilean bottle delivers excellent quality at a fair price.' },
      { type: 'tip', text: 'Pro tip: Always store unopened wine on its side in a cool, dark place. Once opened, re-cork and refrigerate — consume within 3 days for best flavour.' },
      { type: 'h2', text: '5. Casillero del Diablo Cabernet Sauvignon (Chile)' },
      { type: 'p', text: 'Rich dark fruit, a hint of oak, and a long finish. This is the red that converts many beginners into lifelong wine lovers.' },
      { type: 'h2', text: 'What to look for when buying' },
      { type: 'ul', items: [
        'Sweetness level — look for "dry", "off-dry", or "sweet" on the label',
        'Region — New World wines (Chile, Australia, USA) tend to be more fruit-forward and approachable',
        'ABV — beginners often enjoy 11–13% wines; they tend to be lighter',
        'Year — for entry-level wines, freshness matters more than age',
      ]},
      { type: 'p', text: "The most important rule? Drink what you enjoy. Wine appreciation is deeply personal — don't let anyone tell you your palate is wrong." },
    ],
  },
  {
    id: 2,
    title: 'The Art of Mixology: Classic Cocktail Recipes',
    excerpt: 'Learn to make a Negroni, Whiskey Sour, and five other timeless cocktails at home with minimal equipment and maximum flavour.',
    category: 'Recipes',
    date: 'April 28, 2026',
    isoDate: '2026-04-28',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16549766b?w=1200&q=80',
    slug: 'art-of-mixology-cocktail-recipes',
    tags: ['Cocktails', 'Recipes', 'Mixology'],
    author: { name: 'Emeka Obi', role: 'Head Bartender', bio: 'Head bartender at one of Lagos most awarded cocktail bars. Emeka has competed in international mixology competitions and is passionate about elevating Nigeria drinking culture.' },
    content: [
      { type: 'p', text: 'You don\'t need a professional bar to make great cocktails. With a few basic tools — a shaker, a jigger, and a strainer — you can craft drinks that rival any high-end lounge.' },
      { type: 'h2', text: 'Essential Equipment' },
      { type: 'ul', items: ['Cocktail shaker (cobbler or Boston)', 'Jigger (measure)', 'Bar spoon', 'Strainer', 'Muddler', 'Ice cube tray'] },
      { type: 'h2', text: '1. The Negroni' },
      { type: 'p', text: 'Equal parts gin, sweet vermouth, and Campari. Stir with ice, strain into a rocks glass over a large ice cube. Garnish with an orange twist. Bold, bitter, unforgettable.' },
      { type: 'h2', text: '2. Whiskey Sour' },
      { type: 'p', text: '60ml bourbon, 30ml fresh lemon juice, 15ml simple syrup. Shake vigorously with ice. Strain into a glass. Optional: add an egg white before shaking for a silky foam.' },
      { type: 'h2', text: '3. Mojito' },
      { type: 'p', text: 'Muddle 8 mint leaves with 15ml sugar syrup. Add 60ml white rum, 30ml lime juice, and ice. Top with soda water. Stir gently — a Nigerian party staple.' },
      { type: 'tip', text: 'Always use fresh juice. Bottled lemon or lime juice is noticeably inferior in cocktails and will ruin an otherwise great drink.' },
      { type: 'h2', text: '4. Aperol Spritz' },
      { type: 'p', text: '3 parts Prosecco, 2 parts Aperol, 1 splash of soda water. Build over ice in a large wine glass. Garnish with an orange slice. The perfect sundowner.' },
      { type: 'h2', text: '5. Old Fashioned' },
      { type: 'p', text: 'Muddle a sugar cube with 2 dashes Angostura bitters and a splash of water. Add 60ml bourbon or rye. Stir with ice. Strain over a large cube. Orange peel garnish.' },
      { type: 'p', text: 'Start with these five and you\'ll have a cocktail for every mood and occasion. Once comfortable, begin experimenting with ratios, garnishes, and spirit substitutions.' },
    ],
  },
  {
    id: 3,
    title: 'Understanding Beer Styles: A Complete Guide',
    excerpt: 'Lager, IPA, stout, wheat beer — what actually makes each style different? We break it all down with tasting notes and food pairing suggestions.',
    category: 'Beer Guide',
    date: 'April 20, 2026',
    isoDate: '2026-04-20',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=1200&q=80',
    slug: 'understanding-beer-styles',
    tags: ['Beer', 'Guide', 'Craft Beer'],
    author: { name: 'Tunde Fashola', role: 'Craft Beer Specialist', bio: 'Nigeria leading craft beer advocate and founder of a popular beer appreciation club. Tunde has visited over 50 breweries worldwide and hosts regular tasting events in Lagos.' },
    content: [
      { type: 'p', text: 'Beer is the world\'s most consumed alcoholic drink — and yet most people stick to just one or two styles. Expanding your beer horizons is one of the simplest ways to elevate your drinking experience.' },
      { type: 'h2', text: 'Lager' },
      { type: 'p', text: 'The default for most Nigerians. Crisp, clean, and refreshing. Brewed cold with bottom-fermenting yeast. Think Star, Heineken, Trophy. Great with spicy jollof rice or suya.' },
      { type: 'h2', text: 'Stout' },
      { type: 'p', text: 'Dark, roasty, and robust. Brewed with roasted barley for notes of coffee and dark chocolate. Guinness Foreign Extra (brewed in Lagos) is arguably the world\'s most popular stout.' },
      { type: 'h2', text: 'IPA (India Pale Ale)' },
      { type: 'p', text: 'Hop-forward and bitter. IPAs range from piney and resinous to tropical and juicy. An acquired taste — but deeply rewarding once you appreciate the bitterness.' },
      { type: 'h2', text: 'Wheat Beer' },
      { type: 'p', text: 'Light, hazy, and often banana or clove-scented due to the yeast. Erdinger and Paulaner are widely available in Nigeria. Excellent with light salads or grilled fish.' },
      { type: 'tip', text: 'Serve lagers and wheat beers ice cold (2–4°C). Stouts and ales show more complexity slightly warmer (8–12°C). Never serve any beer in a warm glass.' },
      { type: 'h2', text: 'Pairing Beer with Nigerian Food' },
      { type: 'ul', items: [
        'Jollof rice + spicy stew → Lager (cuts through heat)',
        'Suya → IPA (complements smokiness)',
        'Peppered snails → Stout (rich match)',
        'Fried plantain → Wheat beer (fruity harmony)',
        'Asun → Amber ale',
      ]},
    ],
  },
  {
    id: 4,
    title: 'Whiskey Tasting 101: How to Taste Like a Pro',
    excerpt: "Single malt, blended, bourbon — what's the difference? Our expert guide walks you through colour, nose, palate, and finish for any dram.",
    category: 'Spirits Guide',
    date: 'April 12, 2026',
    isoDate: '2026-04-12',
    readTime: '9 min read',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=1200&q=80',
    slug: 'whiskey-tasting-101',
    tags: ['Whiskey', 'Tasting', 'Spirits'],
    author: { name: 'Dr. Chidi Eze', role: 'Whisky Educator', bio: 'A certified whisky educator and PhD in Food Science. Dr. Eze has taught tasting courses to over 2,000 students and writes extensively on the science behind spirit appreciation.' },
    content: [
      { type: 'p', text: 'Tasting whiskey properly is less about rules and more about slowing down and paying attention. Here is a simple framework that works for any style — Scotch, Irish, Bourbon, or Japanese.' },
      { type: 'h2', text: 'Step 1: Colour' },
      { type: 'p', text: 'Hold the glass up to natural light. Pale gold suggests younger spirit or ex-bourbon casks. Deep amber indicates longer ageing or sherry cask influence. Very dark brown often means heavily sherried or wine-finished whisky.' },
      { type: 'h2', text: 'Step 2: Nose' },
      { type: 'p', text: 'Bring the glass to your nose slowly — don\'t plunge in. Let the alcohol evaporate. Try to identify fruit, grain, wood, smoke, or sweet notes. Add a tiny drop of water to open it up further.' },
      { type: 'h2', text: 'Step 3: Palate' },
      { type: 'p', text: 'Take a small sip and hold it on your tongue for 10 seconds. Let it coat your mouth. Is it sweet, spicy, smoky? Light-bodied or rich and oily? Does the flavour evolve as you hold it?' },
      { type: 'h2', text: 'Step 4: Finish' },
      { type: 'p', text: 'After swallowing, note how long the flavour lingers. A long, warming finish indicates quality spirit. Short finishes are common in younger or lighter expressions.' },
      { type: 'tip', text: 'Never add ice to a premium whisky — it numbs your palate and closes up the aroma. A few drops of room-temperature water is the connoisseur\'s choice.' },
      { type: 'h2', text: 'Key Styles at a Glance' },
      { type: 'ul', items: [
        'Single Malt Scotch — one distillery, malted barley only. Expect complexity and terroir.',
        'Blended Scotch — multiple distilleries blended for consistency. Accessible and versatile.',
        'Bourbon — American, at least 51% corn, aged in new charred oak. Sweet and vanilla-rich.',
        'Irish Whiskey — triple-distilled, light and approachable. Great entry point.',
        'Japanese Whisky — precise, balanced, often delicate. Premium pricing reflects craftsmanship.',
      ]},
    ],
  },
  {
    id: 5,
    title: 'How to Host the Perfect House Party in Lagos',
    excerpt: 'From stocking the right drinks fridge to building a playlist, here is our definitive guide to throwing an unforgettable celebration at home.',
    category: 'Entertaining',
    date: 'April 5, 2026',
    isoDate: '2026-04-05',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200&q=80',
    slug: 'host-perfect-house-party',
    tags: ['Party', 'Entertaining', 'Tips'],
    author: { name: 'Sola Adeyemi', role: 'Events Consultant', bio: 'An events consultant with a decade of experience planning everything from intimate dinner parties to large-scale corporate events in Lagos and Abuja.' },
    content: [
      { type: 'p', text: 'Lagos parties have a reputation to uphold. Whether it\'s a birthday, a housewarming, or a spontaneous get-together, the drinks selection can make or break the night.' },
      { type: 'h2', text: 'Calculate Your Drinks Quantity' },
      { type: 'p', text: 'A rough rule: plan for 2 drinks per guest per hour for the first two hours, then 1 per hour after. For a 4-hour party of 20 people, that\'s roughly 120 drinks. Mix spirits, wine, beer, and non-alcoholic options.' },
      { type: 'h2', text: 'The Essential Drinks Menu' },
      { type: 'ul', items: [
        '2–3 spirits (e.g. vodka, whiskey, gin)',
        '1–2 mixers per spirit (tonic, soda, juice)',
        'A signature cocktail or punch made in advance',
        'Red and white wine',
        'Beer selection (at least 2 styles)',
        'Non-alcoholic options for drivers and non-drinkers',
        'Plenty of water and soft drinks',
      ]},
      { type: 'h2', text: 'Ice is Non-Negotiable' },
      { type: 'p', text: 'In Lagos heat, you will always need more ice than you think. Get bags of cube ice for drinks and a separate block for chilling bottles in a cooler.' },
      { type: 'tip', text: 'Pre-batch your signature cocktail the day before. It saves time, stress, and ensures consistency all night. Keep it refrigerated and add ice/carbonation just before serving.' },
      { type: 'h2', text: 'Set Up a Self-Service Bar' },
      { type: 'p', text: 'Lay out spirits, mixers, ice, cups, and garnishes on a dedicated table. Label everything. Guests love the independence, and it frees you to enjoy your own party.' },
    ],
  },
  {
    id: 6,
    title: 'The Best Non-Alcoholic Drinks for Every Occasion',
    excerpt: 'Mocktails, kombuchas, sparkling botanicals — the zero-proof world has never been more exciting. Here are our top picks available in Nigeria.',
    category: 'Lifestyle',
    date: 'March 28, 2026',
    isoDate: '2026-03-28',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=1200&q=80',
    slug: 'best-non-alcoholic-drinks',
    tags: ['Mocktail', 'Non-Alcoholic', 'Wellness'],
    author: { name: 'Ngozi Okafor', role: 'Wellness Writer', bio: 'A wellness journalist and certified nutritionist who covers the intersection of drinks, health, and Nigerian lifestyle. She is passionate about normalising non-alcoholic options in social settings.' },
    content: [
      { type: 'p', text: 'Whether you are sober-curious, pregnant, driving, or simply taking a break, the non-alcoholic drinks market has transformed beyond recognition. Here is what to reach for.' },
      { type: 'h2', text: 'Classic Nigerian Mocktails' },
      { type: 'ul', items: [
        'Chapman — a beloved Nigerian staple. Fanta orange, Fanta lemon, Sprite, grenadine, cucumber, and bitters over ice.',
        'Zobo Punch — dried hibiscus, ginger, pineapple, and citrus. Beautiful colour and packed with antioxidants.',
        'Tiger Nut Smoothie (Kunun Aya) — rich, creamy, and nourishing. Naturally sweet and dairy-free.',
      ]},
      { type: 'h2', text: 'International Zero-Proof Options' },
      { type: 'p', text: 'Seedlip (distilled non-alcoholic spirits), Heineken 0.0, and Lyre\'s spirit alternatives are now available in Nigeria through specialty stores and DrinksHarbour.' },
      { type: 'h2', text: 'Kombucha & Functional Drinks' },
      { type: 'p', text: 'Fermented tea drinks with live cultures. Tangy, lightly fizzy, and great for gut health. The Kevita and GT\'s Kombucha brands have arrived in Lagos supermarkets.' },
      { type: 'tip', text: 'When hosting, always make your mocktails look as beautiful as your cocktails. Garnish with fruit, herbs, and serve in the same glassware — your guests who don\'t drink should feel equally celebrated.' },
    ],
  },
  {
    id: 7,
    title: 'Red vs White Wine: Which Should You Choose?',
    excerpt: 'The age-old question answered once and for all — food pairing rules, temperature tips, and why the best wine is simply the one you enjoy.',
    category: 'Wine Guide',
    date: 'March 20, 2026',
    isoDate: '2026-03-20',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1505275350441-83dcda8eeef5?w=1200&q=80',
    slug: 'red-vs-white-wine',
    tags: ['Wine', 'Food Pairing', 'Guide'],
    author: { name: 'Adaeze Nwosu', role: 'Wine Sommelier', bio: 'A certified sommelier with seven years of experience curating wine lists for Lagos top restaurants. Adaeze trained at the Wine & Spirit Education Trust and believes great wine is for everyone.' },
    content: [
      { type: 'p', text: 'The red vs white debate is as old as wine itself. The truth: neither is better. They are just different tools for different occasions.' },
      { type: 'h2', text: 'Red Wine: What You Need to Know' },
      { type: 'p', text: 'Made from dark grapes, fermented with the skins — which give colour, tannins, and structure. Reds range from light-bodied Pinot Noir to full-bodied Cabernet Sauvignon.' },
      { type: 'h2', text: 'White Wine: What You Need to Know' },
      { type: 'p', text: 'Made from green or yellow grapes (or occasionally red grapes without the skins). Generally lighter, crisper, and higher in acidity. Styles range from bone-dry Chablis to sweet Riesling.' },
      { type: 'h2', text: 'Food Pairing Rules of Thumb' },
      { type: 'ul', items: [
        'Red meat → Red wine (tannins cut through fat)',
        'Fish and seafood → White wine (acidity brightens flavour)',
        'Chicken and pork → Either works — match body to sauce',
        'Spicy food → Off-dry white or rosé (sweetness tames heat)',
        'Cheese → Depends on cheese — soft cheeses love white, hard aged cheeses love red',
      ]},
      { type: 'tip', text: 'Serve whites chilled (8–12°C) and reds at room temperature — which in Lagos means slightly cooler than ambient. A 20-minute fridge stint before serving a red is not a crime.' },
      { type: 'p', text: 'Above all: ignore the rules when your instincts say otherwise. The best pairing is the one that makes you smile.' },
    ],
  },
  {
    id: 8,
    title: 'Gin: The Spirit Having Its Renaissance Moment',
    excerpt: 'From London Dry to contemporary botanicals, gin has exploded in popularity. We look at why — and the best bottles to start your collection.',
    category: 'Spirits Guide',
    date: 'March 12, 2026',
    isoDate: '2026-03-12',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=1200&q=80',
    slug: 'gin-renaissance',
    tags: ['Gin', 'Spirits', 'Trends'],
    author: { name: 'Emeka Obi', role: 'Head Bartender', bio: 'Head bartender at one of Lagos most awarded cocktail bars. Emeka has competed in international mixology competitions and is passionate about elevating Nigeria drinking culture.' },
    content: [
      { type: 'p', text: 'Ten years ago, gin was your grandmother\'s drink. Today it is the spirit of choice for a new generation of drinkers who love botanical complexity and the explosion of craft distilling.' },
      { type: 'h2', text: 'What Makes Gin, Gin?' },
      { type: 'p', text: 'By definition, gin must be flavoured primarily with juniper berries. Everything else — citrus, coriander, angelica, cucumber, rose petals — is up to the distiller. This freedom has produced extraordinary variety.' },
      { type: 'h2', text: 'The Main Styles' },
      { type: 'ul', items: [
        'London Dry — classic, dry, juniper-forward. Think Tanqueray and Gordon\'s.',
        'Contemporary / New Western — juniper takes a backseat to other botanicals. More floral or fruity.',
        'Navy Strength — bottled at 57%+ ABV. Intensely flavoured and powerful.',
        'Old Tom — slightly sweeter, a bridge between dry gin and genever.',
        'Sloe Gin — gin infused with sloe berries. Sweet, fruity, lower ABV.',
      ]},
      { type: 'h2', text: 'The Perfect G&T' },
      { type: 'p', text: '50ml gin, 150ml premium tonic (Fever-Tree or Schweppes), large ice cubes (they melt slower), a garnish that complements the gin\'s botanicals. Serve in a large balloon glass.' },
      { type: 'tip', text: 'Match your garnish to the gin\'s character. Floral gin → rose petals or elderflower. Citrus gin → orange or lemon peel. Spiced gin → cardamom or black pepper.' },
    ],
  },
  {
    id: 9,
    title: 'Ramadan Drinks Guide: Refreshing Iftar Ideas',
    excerpt: 'A curated collection of refreshing, non-alcoholic drinks perfect for breaking your fast — from classic Zobo to sparkling fruit punches.',
    category: 'Lifestyle',
    date: 'March 5, 2026',
    isoDate: '2026-03-05',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=1200&q=80',
    slug: 'ramadan-drinks-guide',
    tags: ['Non-Alcoholic', 'Lifestyle', 'Nigeria'],
    author: { name: 'Fatima Aliyu', role: 'Food & Drink Writer', bio: 'A food and drink writer specialising in Northern Nigerian cuisine and Ramadan traditions. Fatima work has been featured in national publications and cookbooks.' },
    content: [
      { type: 'p', text: 'Breaking your fast with the right drink is both a spiritual and sensory moment. The body craves hydration and gentle sweetness after a day of fasting — these drinks deliver both beautifully.' },
      { type: 'h2', text: 'Start with Water and Dates' },
      { type: 'p', text: 'The Sunnah tradition. Dates provide quick-release natural sugar to restore energy, while water rehydrates the body gently. Always begin with these before any juice or heavier drink.' },
      { type: 'h2', text: 'Zobo (Hibiscus Drink)' },
      { type: 'p', text: 'Boil dried hibiscus flowers with ginger, cloves, and cinnamon. Strain, sweeten with honey or sugar, add pineapple juice, and chill. Rich in vitamin C and antioxidants.' },
      { type: 'h2', text: 'Tamarind Juice (Tsamiya)' },
      { type: 'p', text: 'Soak tamarind pulp in warm water, strain, sweeten, and chill. Tangy, refreshing, and deeply traditional across Northern Nigeria and the broader Muslim world.' },
      { type: 'h2', text: 'Sparkling Fruit Punch' },
      { type: 'p', text: 'Mix equal parts mango juice and pineapple juice. Add fresh mint, a squeeze of lime, and top with chilled sparkling water just before serving. Light, festive, and crowd-pleasing.' },
      { type: 'tip', text: 'Avoid very cold drinks immediately at Iftar — they can cause stomach cramps. Let beverages sit at cool room temperature or add minimal ice for the first drink.' },
      { type: 'h2', text: 'Bissap / Sorrel' },
      { type: 'p', text: 'Popular across West Africa and the Caribbean. Similar to Zobo but often served with mint and ginger. A beautiful deep crimson colour and a tart, refreshing flavour profile.' },
    ],
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  'Wine Guide':    'bg-purple-100 text-purple-700',
  'Spirits Guide': 'bg-amber-100  text-amber-700',
  'Beer Guide':    'bg-yellow-100 text-yellow-700',
  'Recipes':       'bg-orange-100 text-orange-700',
  'Entertaining':  'bg-pink-100   text-pink-700',
  'Lifestyle':     'bg-teal-100   text-teal-700',
};
