import type { TenantFormInput } from '@/validators/create-tenant.schema';
import { PiIdentificationCardBold, PiCreditCardBold, PiPercentBold, PiScalesBold, PiSlidersHorizontalBold } from 'react-icons/pi';
export const TABS = [
  {
    key: 'identity',
    label: 'Identity',
    icon: PiIdentificationCardBold,
    fields: [
      'name',
      'slug',
      'contactEmail',
      'contactPhone',
      'country',
      'primaryColor',
      'ownerName',
      'ownerEmail',
      'ownerPhone',
    ],
  },
  {
    key: 'billing',
    label: 'Billing',
    icon: PiCreditCardBold,
    fields: [
      'plan',
      'subscriptionStatus',
      'paystackCustomerId',
      'paystackSubscriptionCode',
      'paystackPlanCode',
      'trialEndsAt',
      'currentPeriodStart',
      'currentPeriodEnd',
    ],
  },
  {
    key: 'revenue',
    label: 'Revenue',
    icon: PiPercentBold,
    fields: [
      'revenueModel',
      'markupPercentage',
      'commissionPercentage',
      'platformMarkupPercentage',
      'packMarkupPercentage',
      'packCommissionPercentage',
      'packRateMinUnits',
      'customPricingNote',
    ],
  },
  {
    key: 'legal',
    label: 'Legal & KYC',
    icon: PiScalesBold,
    fields: [
      'businessType',
      'cacNumber',
      'tin',
      'idType',
      'idNumber',
      'nafdacRequired',
      'nafdacNumber',
      'bankName',
      'bankAccountNumber',
      'bankAccountName',
      'bankAccounts',
      'applicationDescription',
    ],
  },
  {
    key: 'operations',
    label: 'Operations',
    icon: PiSlidersHorizontalBold,
    fields: [
      'addressStreet',
      'addressCity',
      'addressLga',
      'addressState',
      'addressZipCode',
      'addressCountry',
      'defaultCurrency',
      'supportedCurrencies',
      'psDefaultBillControlPolicy',
      'psApprovalThreshold',
      'psDefaultPaymentTerms',
      'psDefaultReceivingLocation',
      'psRfqValidityDays',
      'psDefaultLeadTimeDays',
      'psEnable3WayMatching',
      'psRequirePOApproval',
      'psAutoGenerateBill',
      'psAllowPartialReceipts',
      'psLockConfirmedOrders',
      'notes',
    ],
  },
] as const;

export const DEFAULT_VALUES: Partial<TenantFormInput> = {
  status: 'pending',
  plan: 'free_trial',
  subscriptionStatus: 'trialing',
  revenueModel: 'markup',
  markupPercentage: 40,
  commissionPercentage: 12,
  platformMarkupPercentage: 15,
  defaultCurrency: 'NGN',
  enforceAgeVerification: true,
  isSystemTenant: false,
  primaryColor: '#1a202c',
  psEnable3WayMatching: true,
  psRequirePOApproval: true,
  psApprovalThreshold: 0,
  psAutoGenerateBill: false,
  psAllowPartialReceipts: true,
  psLockConfirmedOrders: false,
  psDefaultBillControlPolicy: 'received',
  nafdacRequired: false,
  bankAccounts: [],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────
