// schemas/MediaItem.schema.js

const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * Reusable Media Item Schema for images and videos
 * Used across Product, SubProduct, Size, Brand, Tenant, etc.
 */
const MediaItemSchema = new Schema(
  {
    url: {
      type: String,
      required: true,
      validate: {
        validator: function (v) {
          return /^https?:\/\/.+/.test(v);
        },
        message: 'URL must be a valid HTTP/HTTPS URL',
      },
    },
    
    // Cloudinary-specific fields
    publicId: {
      type: String,
      required: true,
      index: true,
    },
    
    resourceType: {
      type: String,
      enum: ['image', 'video', 'raw'],
      default: 'image',
    },
    
    format: {
      type: String, // jpg, png, webp, mp4, etc.
    },
    
    width: {
      type: Number,
    },
    
    height: {
      type: Number,
    },
    
    size: {
      type: Number, // File size in bytes
    },
    
    // Alternative text for accessibility
    alt: {
      type: String,
      trim: true,
      maxlength: 200,
    },
    
    // Display order (for galleries)
    order: {
      type: Number,
      default: 0,
      min: 0,
    },
    
    // Primary image flag
    isPrimary: {
      type: Boolean,
      default: false,
    },
    
    // Thumbnail URL (auto-generated by Cloudinary)
    thumbnail: {
      type: String,
    },
    
    // Metadata
    uploadedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },
    
    uploadedAt: {
      type: Date,
      default: Date.now,
    },
    
    // Tags for organization
    tags: [String],
    
    // Optional caption
    caption: {
      type: String,
      trim: true,
      maxlength: 500,
    },
  },
  { 
    _id: false, // Don't create separate _id for subdocuments
    timestamps: false 
  }
);

// Virtual for Cloudinary transformations
MediaItemSchema.virtual('optimizedUrl').get(function () {
  if (!this.publicId) return this.url;
  
  // Generate optimized URL with Cloudinary transformations
  const baseUrl = 'https://res.cloudinary.com';
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  
  if (!cloudName) return this.url;
  
  // Auto-format, auto-quality, responsive
  return `${baseUrl}/${cloudName}/image/upload/f_auto,q_auto,w_800/${this.publicId}`;
});

// Virtual for thumbnail
MediaItemSchema.virtual('thumbnailUrl').get(function () {
  if (this.thumbnail) return this.thumbnail;
  if (!this.publicId) return this.url;
  
  const baseUrl = 'https://res.cloudinary.com';
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  
  if (!cloudName) return this.url;
  
  // Small thumbnail transformation
  return `${baseUrl}/${cloudName}/image/upload/f_auto,q_auto,w_200,h_200,c_fill/${this.publicId}`;
});

module.exports = MediaItemSchema;