export const routes = {
  dashboard: '/ecommerce',
  signIn: '/signin',
  signUp: '/signup',
  warehouses: {
    list: '/warehouses',
    analysis: '/warehouses/analysis',
    detail: (id: string) => `/warehouses/${id}`,
    // Warehouse / inventory settings (sections of the central settings page)
    settings: '/settings#warehouses',
    inventorySettings: '/settings#pos_inventory',
  },
  inventory: {
    index: '/inventory',
    // Operations
    transfers: '/inventory/transfers',
    receipts: '/inventory/receipts',
    deliveries: '/inventory/deliveries',
    internal: '/inventory/internal',
    adjustments: '/inventory/adjustments',
    physicalInventory: '/inventory/physical-inventory',
    scrap: '/inventory/scrap',
    procurement: '/inventory/procurement',
    replenishment: '/inventory/replenishment',
    // Reporting
    stock: '/inventory/stock',
    locations: '/inventory/locations',
    valuation: '/inventory/valuation',
    movesHistory: '/inventory/moves',
    // Configuration (backed pages live elsewhere; placeholders live here)
    settings: '/settings#warehouses',
    operationTypes: '/inventory/configuration/operation-types',
    configLocations: '/inventory/configuration/locations',
    storageCategories: '/inventory/configuration/storage-categories',
    putawayRules: '/inventory/configuration/putaway-rules',
    attributes: '/inventory/configuration/attributes',
    deliveryMethods: '/inventory/configuration/delivery-methods',
    packageTypes: '/inventory/configuration/package-types',
  },
  employees: {
    list: '/employees',
    detail: (id: string) => `/employees/${id}`,
  },
  contacts: {
    list: '/contacts',
    // `key` is the "source:id" handle returned on each Contact.
    detail: (key: string) => `/contacts/${key}`,
  },
  eCommerce: {
    dashboard: '/ecommerce',
    products: '/products',
    createProduct: '/products/create',
    productDetails: (slug: string) => `/products/${slug}`,
    ediProduct: (slug: string) => `/products/${slug}/edit`,
    subProducts: '/sub-products',
    createSubProduct: '/sub-products/create',
    subProductDetails: (slug: string) => `/sub-products/${slug}`,
    editSubProduct: (slug: string) => `/sub-products/${slug}/edit`,
    purchases: '/purchases',
    createPurchase: '/purchases/create',
    purchaseReceipt: (id: string) => `/purchases/receipt/${id}`,
    purchaseDetails: (id: string) => `/purchases/${id}`,
    editPurchase: (id: string) => `/purchases/${id}/edit`,
    purchaseVendors: '/purchases/vendors',
    receivePurchase: '/purchases/receive',
    validateReceipt: '/purchases/validate',
    // Vendor Bills Routes
    vendorBills: '/purchases/bills',
    createVendorBill: '/purchases/bills/create',
    vendorBillDetails: (id: string) => `/purchases/bills/${id}`,
    // Vendor Returns Routes
    vendorReturns: '/purchases/returns',
    createVendorReturn: '/purchases/returns/create',
    vendorReturnDetails: (id: string) => `/purchases/returns/${id}`,
    // Purchase Analytics
    purchaseAnalytics: '/purchases/analytics',
    // Purchase Settings
    purchaseSettings: '/settings#purchases',
    // Purchase Agreements (Blanket Orders)
    purchaseAgreements: '/purchases/agreements',
    createPurchaseAgreement: '/purchases/agreements/create',
    purchaseAgreementDetails: (id: string) => `/purchases/agreements/${id}`,
    // Vendor Pricelists
    vendorPricelists: '/purchases/pricelists',
    createVendorPricelist: '/purchases/pricelists/create',
    vendorPricelistDetails: (id: string) => `/purchases/pricelists/${id}`,
    // UOM Conversions
    uomConversions: '/purchases/uom-conversions',
    createUomConversion: '/purchases/uom-conversions/create',
    // Exchange Rates
    exchangeRates: '/purchases/exchange-rates',
    createExchangeRate: '/purchases/exchange-rates/create',
    // Stock Transfers
    stockTransfers: '/purchases/transfers',
    createStockTransfer: '/purchases/transfers/create',
    stockTransferDetails: (id: string) => `/purchases/transfers/${id}`,
    editStockTransfer: (id: string) => `/purchases/transfers/${id}/edit`,
    // Sales (quotations -> orders -> fulfillment -> returns)
    sales: '/sales',
    createSale: '/sales/create',
    salesQuotations: '/sales/quotations',
    salesOrders: '/sales/orders',
    salesDetails: (id: string) => `/sales/${id}`,
    salesEdit: (id: string) => `/sales/${id}/edit`,
    salesPrint: (id: string, type: 'quotation' | 'proforma') =>
      `/sales/${id}/print?type=${type}`,
    salesFulfillList: '/sales/fulfill',
    salesFulfillDetails: (id: string) => `/sales/fulfill/${id}`,
    salesReturns: '/sales/returns',
    createSalesReturn: '/sales/returns/create',
    salesReturnDetails: (id: string) => `/sales/returns/${id}`,
    categories: '/categories',
    createCategory: '/categories/create',
    editCategory: (id: string) => `/categories/${id}/edit`,
    categoryProducts: (id: string) => `/categories/${id}`,
    subCategories: '/sub-categories',
    createSubCategory: '/sub-categories/create',
    editSubCategory: (id: string) => `/sub-categories/${id}/edit`,
    subCategoryProducts: (id: string) => `/sub-categories/${id}`,
    brands: '/brands',
    createBrand: '/brands/create',
    editBrand: (id: string) => `/brands/${id}/edit`,
    brandProducts: (id: string) => `/brands/${id}`,
    tenants: '/tenants',
    createTenant: '/tenants/create',
    tenantDetails: (id: string) => `/tenants/${id}`,
    editTenant: (id: string) => `/tenants/${id}/edit`,
    orders: '/ecommerce/orders',
    createOrder: '/ecommerce/orders/create',
    orderDetails: (id: string) => `/ecommerce/orders/${id}`,
    editOrder: (id: string) => `/ecommerce/orders/${id}/edit`,
    reviews: '/ecommerce/reviews',
    promotions: '/ecommerce/promotions',
    createPromotion: '/ecommerce/promotions/create',
    editPromotion: (id: string) => `/ecommerce/promotions/${id}/edit`,
    banners: '/banners',
    createBanner: '/banners/create',
    editBanner: (id: string) => `/banners/${id}/edit`,
    bannerDetails: (id: string) => `/banners/${id}`,
    shop: '/ecommerce/shop',
    cart: '/ecommerce/cart',
    checkout: '/ecommerce/checkout',
    trackingId: (id: string) => `/ecommerce/tracking/${id}`,
  },
  blog: {
    list: '/blog',
    create: '/blog/create',
    edit: (id: string) => `/blog/${id}/edit`,
  },
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
  logistics: {
    dashboard: '/logistics',
    shipmentList: '/logistics/shipments',
    customerProfile: '/logistics/customer-profile',
    createShipment: '/logistics/shipments/create',
    editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  appointment: {
    dashboard: '/appointment',
    appointmentList: '/appointment/list',
  },
  crm: {
    dashboard: '/crm',
  },
  affiliate: {
    dashboard: 'https://isomorphic-dnd.vercel.app',
  },
  storeAnalytics: {
    dashboard: '/store-analytics',
  },
  bidding: {
    dashboard: '/bidding',
  },
  executive: {
    dashboard: '/executive',
  },
  project: {
    dashboard: '/project',
  },
  socialMedia: {
    dashboard: '/social-media',
  },
  jobBoard: {
    dashboard: '/job-board',
    jobFeed: '/job-board/feed',
  },
  analytics: '/analytics',
  financial: {
    dashboard: '/financial',
  },
  podcast: {
    dashboard: '/podcast',
  },
  file: {
    dashboard: '/file',
    manager: '/file-manager',
    upload: '/file-manager/upload',
    create: '/file-manager/create',
  },
  pos: {
    index: '/point-of-sale',
    sell: '/point-of-sale/sell',
    history: '/point-of-sale/history',
    sessions: '/point-of-sale/sessions',
    login: '/point-of-sale/login',
    lock: '/point-of-sale/lock',
    cashiers: '/point-of-sale/cashiers',
    settings: '/settings#point_of_sale',
    loyalty: '/point-of-sale/loyalty',
    orders: '/point-of-sale/orders',
    orderAnalysis: '/point-of-sale/order-analysis',
    salesDetails: '/point-of-sale/sales-details',
    sessionReport: '/point-of-sale/session-report',
    pricelists: '/pos/pricelists',
    combos: '/point-of-sale/combos',
    // Standalone cashier POS (uses pos_token, not admin JWT)
    cashierLogin: '/pos/login',
    cashierDashboard: '/pos/dashboard',
    cashierSell: '/pos/sell',
    cashierSellOrders: '/pos/sell/orders',
  },
  eventCalendar: '/event-calendar',
  rolesPermissions: '/roles-permissions',
  invoice: {
    home: '/invoice',
    create: '/invoice/create',
    details: (id: string) => `/invoice/${id}`,
    edit: (id: string) => `/invoice/${id}/edit`,
    builder: '/invoice/builder',
  },
  imageViewer: '/image-viewer',
  widgets: {
    cards: '/widgets/cards',
    icons: '/widgets/icons',
    charts: '/widgets/charts',
    maps: '/widgets/maps',
    banners: '/widgets/banners',
  },
  tables: {
    basic: '/tables/basic',
    collapsible: '/tables/collapsible',
    enhanced: '/tables/enhanced',
    pagination: '/tables/pagination',
    search: '/tables/search',
    stickyHeader: '/tables/sticky-header',
    resizable: '/tables/resizable',
    pinning: '/tables/pinning',
    dnd: '/tables/dnd',
  },
  multiStep: '/multi-step',
  multiStep2: '/multi-step-2',
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  billing: '/settings/billing',
  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/welcome',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',
  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up-2',
    signUp3: '/auth/sign-up-3',
    signUp4: '/auth/sign-up-4',
    signUp5: '/auth/sign-up-5',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in-2',
    signIn3: '/auth/sign-in-3',
    signIn4: '/auth/sign-in-4',
    signIn5: '/auth/sign-in-5',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword2: '/auth/forgot-password-2',
    forgotPassword3: '/auth/forgot-password-3',
    forgotPassword4: '/auth/forgot-password-4',
    forgotPassword5: '/auth/forgot-password-5',
    // reset password (token from the emailed link)
    resetPassword: (token: string) => `/auth/reset-password/${token}`,
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp-2',
    otp3: '/auth/otp-3',
    otp4: '/auth/otp-4',
    otp5: '/auth/otp-5',
  },
};
